/**
 * Agile-encrypted OOXML fixture, base64-embedded.
 *
 * A minimal single-paragraph "Hello encrypted" .docx, Agile-encrypted
 * ([MS-OFFCRYPTO] §2.3.4) with password `test` and **spinCount 0** (so tests
 * derive keys instantly). It was generated by a spec-faithful Python encryptor
 * + a correct CFB writer and cross-verified: the independent `msoffcrypto-tool`
 * decryptor recovers the exact original .docx from it. Embedding the bytes (not
 * the .docx) keeps binary Office files out of git per repo policy.
 *
 * Deterministic material (all salts fixed) so the derived-key vectors below are
 * stable:
 *   - keyData.saltValue  = 000102...0f (16 bytes)
 *   - password salt      = 101112...1f (16 bytes)
 * See `packages/core/src/crypto/agile.test.ts` for the pinned vectors.
 */
export const ENCRYPTED_DOCX_SPIN0_BASE64 =
  '0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAEAAAAgAAAAEAAAD+////AAAA' +
  'AAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '///////////////////////////////////////////////////////////////////////////////////9/////v////7///8E' +
  'AAAABQAAAAYAAAAHAAAA/v//////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUB//////////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAwAAAEAJAAAAAAAARQBuAGMAcgB5AHAAdABlAGQAUABhAGMAawBhAGcAZQAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAACIAAgECAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyAMA' +
  'AAAAAABFAG4AYwByAHkAcAB0AGkAbwBuAEkAbgBmAG8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgACAf//' +
  '/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAEBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAA' +
  'AAsAAAAMAAAADQAAAA4AAAAPAAAA/v///xEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0A' +
  'AAAeAAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAA/v//////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////+4AwAAAAAAAK5SbjfH9ZjT0+DJVaVzZ1kvqIwZc2VpA6XLbl0gR2MbcWACFYBG1Xz7G1tC' +
  'zHBPzHTogP6nUA6kVrZ9J9khS3vgAHblhSiCP+N6lvCIPAoAf3lANJAqUp5zD655bRt48uSLOU2XZdvlH2Nx+7D7Y5qn8YhsXDjw' +
  'UH+GkkgI5MrNuma+YgYTORaJ+7yJLNuNbg7Ny4TMrPuXFWtN4tk6fZ3CohRbwAx1P4QLrBGmudKvEjbvhw8mtyV3PvRIKUmkZ4CC' +
  '5Whmza81/qpTHfmFcOGiYOlVMYTl+3HZvKs7nTSFgQzED1ZMvWB4nBU8oWQHpoXy6+RQvqnIbtTie9Z5Yk+7GVlWYfaMzPJv6wVS' +
  'KI+TkbpgwXN2NF6SK/TsTR8b8/AHdNBksOCilYH4Xx5kz4WsP8DF+jcVf4PXNYOxdb3Mp/+Pvnz+/TR+Q2wnNhjT3mMd0eyJUg2a' +
  'aZUPlTceIJ4LrZrU5MRagEk7UFXGJHqMDnzZsgVAuLrThOeno+07SKT0jF5Q+WlMR/hdXVcohxUWbhgFLQ9pVgMF7KjzxPYxPrxb' +
  'DxjnhBuCZP5SgZ34AtojB4gkOV2f4EZlkGIQ/8WSKVY6mR+mTXBpI/9VlgByqgrglP4v/XVy3Xv72KvbAWKpSUFH3mpK5XZtyC9z' +
  'XzijsupCcoZMkkD9qbg1joOXQib+9luk7M6PptZXTYPsoc7lN5Yd25+VapfjINiNIGeOgwz8XK07ocbOUdSYjH/HvgZaskFk9yM3' +
  '4wCkQQualNdVP+SC++dfHuB2SSi6J9UPFDyn6HPwlBDVDDujB119XrVg+bsqlf8d8wddbMxAk3dfRUTrrF/gwhvM0nLAvquzuqOp' +
  '2pU4dYYfA8Qno1R6Us5zwG19fj+bBZOr1K/qrcf10ZHyd71OIbiRwiqb3pierXGreIPRBs/2wMvC9jjnOrWnDBhqXDfwPKfWRJ5W' +
  'jjvsZHNMLFSjFHSO9cSF5IVOwUj/zb8OSvydxWYp9mbTmSiCNxtxsZ6vE+0sR9XInKmnPLcz0p5p6xSyv63AVOHS1Tt2jyfYXh4N' +
  'vh8RDl3amL6VbDcUWe1wnQ3etSfqCA3RebKwW6nglpwLkyP5EkjjuQIKYmbVM9Q1iFFkFUSi37XwqIcJj/dpOHS5DQD44QMZbK7w' +
  '+CjHVm6pPkEFBvH2M1ycYuO04stG6irnm2frp/o+aKegR7HTCFEMZPz9HQhOci6tXt2lEJIkXMQ2EtOa2Ho1w4h69ZtxmncLw8VF' +
  'qkMf4uR7SfFAhMgZGYzHggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAE' +
  'AEAAAAA8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQo8ZW5jcnlwdGlvbiB4' +
  'bWxucz0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNi9lbmNyeXB0aW9uIiB4bWxuczpwPSJodHRwOi8v' +
  'c2NoZW1hcy5taWNyb3NvZnQuY29tL29mZmljZS8yMDA2L2tleUVuY3J5cHRvci9wYXNzd29yZCIgeG1sbnM6Yz0iaHR0cDovL3Nj' +
  'aGVtYXMubWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNi9rZXlFbmNyeXB0b3IvY2VydGlmaWNhdGUiPjxrZXlEYXRhIHNhbHRTaXpl' +
  'PSIxNiIgYmxvY2tTaXplPSIxNiIga2V5Qml0cz0iMjU2IiBoYXNoU2l6ZT0iNjQiIGNpcGhlckFsZ29yaXRobT0iQUVTIiBjaXBo' +
  'ZXJDaGFpbmluZz0iQ2hhaW5pbmdNb2RlQ0JDIiBoYXNoQWxnb3JpdGhtPSJTSEE1MTIiIHNhbHRWYWx1ZT0iQUFFQ0F3UUZCZ2NJ' +
  'Q1FvTERBME9Edz09Ii8+PGRhdGFJbnRlZ3JpdHkgZW5jcnlwdGVkSG1hY0tleT0iaEZKV1dQd09RbUFZTGcvcHhzRXJ2b3ZGWTFD' +
  'OXl0aE5TdTM0M0dGYkNHOU1IRjlkcC9yakV3MlVWUEJHUG80K1pyQitLWmlhZWwwY0x5VU5MVHBMNFE9PSIgZW5jcnlwdGVkSG1h' +
  'Y1ZhbHVlPSJ3K2tCZk1YU0ROU1Y0MFJzUTJmVGZraURPQzhzK1NtZWtvWEt2TUx5cVRlSkJEbjdWM01UcTU1OURNVEc4ZDRPS2Rr' +
  'emlvcC93amhTUHI4TysyY3ZXdz09Ii8+PGtleUVuY3J5cHRvcnM+PGtleUVuY3J5cHRvciB1cmk9Imh0dHA6Ly9zY2hlbWFzLm1p' +
  'Y3Jvc29mdC5jb20vb2ZmaWNlLzIwMDYva2V5RW5jcnlwdG9yL3Bhc3N3b3JkIj48cDplbmNyeXB0ZWRLZXkgc3BpbkNvdW50PSIw' +
  'IiBzYWx0U2l6ZT0iMTYiIGJsb2NrU2l6ZT0iMTYiIGtleUJpdHM9IjI1NiIgaGFzaFNpemU9IjY0IiBjaXBoZXJBbGdvcml0aG09' +
  'IkFFUyIgY2lwaGVyQ2hhaW5pbmc9IkNoYWluaW5nTW9kZUNCQyIgaGFzaEFsZ29yaXRobT0iU0hBNTEyIiBzYWx0VmFsdWU9IkVC' +
  'RVNFeFFWRmhjWUdSb2JIQjBlSHc9PSIgZW5jcnlwdGVkVmVyaWZpZXJIYXNoSW5wdXQ9IkxtRzhobk1hbDg2QXYrVEkyQnlteEE9' +
  'PSIgZW5jcnlwdGVkVmVyaWZpZXJIYXNoVmFsdWU9IklPZ2xOaDNnand6Wk9zaHpJNkQxak9ycklQUDJYYXNzR2o1RGFSWXNZaHRV' +
  'eGVtR05nMG9RQkhoNk1CVUlpUlkzMFIremRnZHJhQkJtN0pQaTM2WFF3PT0iIGVuY3J5cHRlZEtleVZhbHVlPSJ2cmF2aUt3UTRY' +
  'd1VaOVBHUkkrNDBiTzFsdXNadm1ZSW9VNERpVFpxWXVZPSIvPjwva2V5RW5jcnlwdG9yPjwva2V5RW5jcnlwdG9ycz48L2VuY3J5' +
  'cHRpb24+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

/** Decode the embedded fixture to bytes. */
export function encryptedDocxSpin0(): Uint8Array {
  const bin = atob(ENCRYPTED_DOCX_SPIN0_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
