/**
 * Agile-encrypted OOXML fixture, base64-embedded.
 *
 * A minimal single-paragraph "Hello encrypted" .docx, Agile-encrypted
 * ([MS-OFFCRYPTO] §2.3.4) with password `test` and **spinCount 0** (so tests
 * derive keys instantly). It was generated by a spec-faithful Python encryptor
 * + a correct CFB writer and cross-verified: the independent `msoffcrypto-tool`
 * decryptor recovers the exact original .docx from it. Embedding the bytes (not
 * the .docx) keeps binary Office files out of git per repo policy.
 *
 * Deterministic material (all salts fixed) so the derived-key vectors below are
 * stable:
 *   - keyData.saltValue  = 000102...0f (16 bytes)
 *   - password salt      = 101112...1f (16 bytes)
 * See `packages/core/src/crypto/agile.test.ts` for the pinned vectors.
 *
 * ## Regenerating this fixture
 *
 * There is no script checked into the repo (Office binaries are not committed,
 * and the generator is a one-off, not a build step) — regeneration means
 * re-deriving the two pieces below from scratch:
 *
 *   1. **Plaintext container.** A minimal .docx built directly with `zipfile`
 *      (no python-docx dependency): a stored/deflated ZIP with the standard
 *      OOXML parts (`[Content_Types].xml`, `_rels/.rels`,
 *      `word/document.xml`, `word/_rels/document.xml.rels`) and a single
 *      paragraph run containing the literal text "Hello encrypted".
 *   2. **Agile encryptor**, implementing [MS-OFFCRYPTO] §2.3.4 directly from
 *      the spec formulas — no third-party encryption library:
 *        - `H0 = Hash(saltValue || UTF-16LE(password))`, then `spinCount`
 *          rounds of `H(n) = Hash(LE32(n) || H(n-1))` (§2.3.4.7). With
 *          `spinCount = 0` this loop is skipped entirely, which is why key
 *          derivation in tests is instant.
 *        - Per-purpose block keys XORed onto the final iterated hash before
 *          the last hash step (`blockKey`, §2.3.4.9): verifier input
 *          `fea7d2763b4b9e79`, verifier hash `d7aa0f6d3061344e`, key value
 *          `146e0be7abacd0d6`, HMAC key `5fb2ad010cb9e1f6`, HMAC value
 *          `a0677f02b22c8433`.
 *        - `EncryptedPackage` container (§2.3.4.15): `LE64(plaintextSize)`
 *          prefix, then the plaintext ZIP split into 4096-byte segments, each
 *          AES-CBC encrypted with an IV of
 *          `H(keyData.saltValue || LE32(segmentIndex))` truncated/zero-padded
 *          to `blockSize`.
 *        - The `EncryptionInfo` stream is assembled by hand: an 8-byte
 *          `vMajor=4, vMinor=4` header + 4-byte reserved (`0x00000040`),
 *          followed by the `<encryption>` XML descriptor (`keyData`,
 *          `keyEncryptors/keyEncryptor/encryptedKey`, `dataIntegrity`) with
 *          the computed salts / verifier / key-value / HMAC fields base64'd
 *          in.
 *      Independently cross-verified by running the output through
 *      `msoffcrypto-tool` (a maintained, spec-independent Python decryptor)
 *      and confirming it recovers the original "Hello encrypted" plaintext —
 *      this catches encoder bugs a self-consistent round-trip would hide.
 *   3. **CFB container.** The `EncryptionInfo` and `EncryptedPackage` streams
 *      are written into a compound file (OLE2 / [MS-CFB]) with a real FAT /
 *      mini-FAT layout (mirrored for tests by
 *      `packages/core/src/testing/cfb-fixture.ts`'s `buildCfbWithStreams`).
 *   4. Base64-encode the resulting CFB bytes into `ENCRYPTED_DOCX_SPIN0_BASE64`
 *      below.
 *
 * Fixed parameters to preserve if regenerating (changing any of these
 * invalidates the pinned vectors in `agile.test.ts`):
 *   - password: `test`
 *   - hashAlgorithm: `SHA512`, keyBits: `256`, cipherAlgorithm: `AES`,
 *     cipherChaining: `ChainingModeCBC`, blockSize: `16`, saltSize: `16`
 *   - spinCount: `0`
 *   - keyData.saltValue: `00 01 02 ... 0f` (16 bytes)
 *   - password-encryptor saltValue: `10 11 12 ... 1f` (16 bytes)
 */
export const ENCRYPTED_DOCX_SPIN0_BASE64 =
  '0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAEAAAAgAAAAEAAAD+////AAAA' +
  'AAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '///////////////////////////////////////////////////////////////////////////////////9/////v////7///8E' +
  'AAAABQAAAAYAAAAHAAAA/v//////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUB//////////8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAwAAAEAJAAAAAAAARQBuAGMAcgB5AHAAdABlAGQAUABhAGMAawBhAGcAZQAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAACIAAgECAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyAMA' +
  'AAAAAABFAG4AYwByAHkAcAB0AGkAbwBuAEkAbgBmAG8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgACAf//' +
  '/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAEBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAA' +
  'AAsAAAAMAAAADQAAAA4AAAAPAAAA/v///xEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0A' +
  'AAAeAAAAHwAAACAAAAAhAAAAIgAAACMAAAAkAAAA/v//////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////////' +
  '//////////////////////////////+4AwAAAAAAAK5SbjfH9ZjT0+DJVaVzZ1kvqIwZc2VpA6XLbl0gR2MbcWACFYBG1Xz7G1tC' +
  'zHBPzHTogP6nUA6kVrZ9J9khS3vgAHblhSiCP+N6lvCIPAoAf3lANJAqUp5zD655bRt48uSLOU2XZdvlH2Nx+7D7Y5qn8YhsXDjw' +
  'UH+GkkgI5MrNuma+YgYTORaJ+7yJLNuNbg7Ny4TMrPuXFWtN4tk6fZ3CohRbwAx1P4QLrBGmudKvEjbvhw8mtyV3PvRIKUmkZ4CC' +
  '5Whmza81/qpTHfmFcOGiYOlVMYTl+3HZvKs7nTSFgQzED1ZMvWB4nBU8oWQHpoXy6+RQvqnIbtTie9Z5Yk+7GVlWYfaMzPJv6wVS' +
  'KI+TkbpgwXN2NF6SK/TsTR8b8/AHdNBksOCilYH4Xx5kz4WsP8DF+jcVf4PXNYOxdb3Mp/+Pvnz+/TR+Q2wnNhjT3mMd0eyJUg2a' +
  'aZUPlTceIJ4LrZrU5MRagEk7UFXGJHqMDnzZsgVAuLrThOeno+07SKT0jF5Q+WlMR/hdXVcohxUWbhgFLQ9pVgMF7KjzxPYxPrxb' +
  'DxjnhBuCZP5SgZ34AtojB4gkOV2f4EZlkGIQ/8WSKVY6mR+mTXBpI/9VlgByqgrglP4v/XVy3Xv72KvbAWKpSUFH3mpK5XZtyC9z' +
  'XzijsupCcoZMkkD9qbg1joOXQib+9luk7M6PptZXTYPsoc7lN5Yd25+VapfjINiNIGeOgwz8XK07ocbOUdSYjH/HvgZaskFk9yM3' +
  '4wCkQQualNdVP+SC++dfHuB2SSi6J9UPFDyn6HPwlBDVDDujB119XrVg+bsqlf8d8wddbMxAk3dfRUTrrF/gwhvM0nLAvquzuqOp' +
  '2pU4dYYfA8Qno1R6Us5zwG19fj+bBZOr1K/qrcf10ZHyd71OIbiRwiqb3pierXGreIPRBs/2wMvC9jjnOrWnDBhqXDfwPKfWRJ5W' +
  'jjvsZHNMLFSjFHSO9cSF5IVOwUj/zb8OSvydxWYp9mbTmSiCNxtxsZ6vE+0sR9XInKmnPLcz0p5p6xSyv63AVOHS1Tt2jyfYXh4N' +
  'vh8RDl3amL6VbDcUWe1wnQ3etSfqCA3RebKwW6nglpwLkyP5EkjjuQIKYmbVM9Q1iFFkFUSi37XwqIcJj/dpOHS5DQD44QMZbK7w' +
  '+CjHVm6pPkEFBvH2M1ycYuO04stG6irnm2frp/o+aKegR7HTCFEMZPz9HQhOci6tXt2lEJIkXMQ2EtOa2Ho1w4h69ZtxmncLw8VF' +
  'qkMf4uR7SfFAhMgZGYzHggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAE' +
  'AEAAAAA8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCIgc3RhbmRhbG9uZT0ieWVzIj8+DQo8ZW5jcnlwdGlvbiB4' +
  'bWxucz0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNi9lbmNyeXB0aW9uIiB4bWxuczpwPSJodHRwOi8v' +
  'c2NoZW1hcy5taWNyb3NvZnQuY29tL29mZmljZS8yMDA2L2tleUVuY3J5cHRvci9wYXNzd29yZCIgeG1sbnM6Yz0iaHR0cDovL3Nj' +
  'aGVtYXMubWljcm9zb2Z0LmNvbS9vZmZpY2UvMjAwNi9rZXlFbmNyeXB0b3IvY2VydGlmaWNhdGUiPjxrZXlEYXRhIHNhbHRTaXpl' +
  'PSIxNiIgYmxvY2tTaXplPSIxNiIga2V5Qml0cz0iMjU2IiBoYXNoU2l6ZT0iNjQiIGNpcGhlckFsZ29yaXRobT0iQUVTIiBjaXBo' +
  'ZXJDaGFpbmluZz0iQ2hhaW5pbmdNb2RlQ0JDIiBoYXNoQWxnb3JpdGhtPSJTSEE1MTIiIHNhbHRWYWx1ZT0iQUFFQ0F3UUZCZ2NJ' +
  'Q1FvTERBME9Edz09Ii8+PGRhdGFJbnRlZ3JpdHkgZW5jcnlwdGVkSG1hY0tleT0iaEZKV1dQd09RbUFZTGcvcHhzRXJ2b3ZGWTFD' +
  'OXl0aE5TdTM0M0dGYkNHOU1IRjlkcC9yakV3MlVWUEJHUG80K1pyQitLWmlhZWwwY0x5VU5MVHBMNFE9PSIgZW5jcnlwdGVkSG1h' +
  'Y1ZhbHVlPSJ3K2tCZk1YU0ROU1Y0MFJzUTJmVGZraURPQzhzK1NtZWtvWEt2TUx5cVRlSkJEbjdWM01UcTU1OURNVEc4ZDRPS2Rr' +
  'emlvcC93amhTUHI4TysyY3ZXdz09Ii8+PGtleUVuY3J5cHRvcnM+PGtleUVuY3J5cHRvciB1cmk9Imh0dHA6Ly9zY2hlbWFzLm1p' +
  'Y3Jvc29mdC5jb20vb2ZmaWNlLzIwMDYva2V5RW5jcnlwdG9yL3Bhc3N3b3JkIj48cDplbmNyeXB0ZWRLZXkgc3BpbkNvdW50PSIw' +
  'IiBzYWx0U2l6ZT0iMTYiIGJsb2NrU2l6ZT0iMTYiIGtleUJpdHM9IjI1NiIgaGFzaFNpemU9IjY0IiBjaXBoZXJBbGdvcml0aG09' +
  'IkFFUyIgY2lwaGVyQ2hhaW5pbmc9IkNoYWluaW5nTW9kZUNCQyIgaGFzaEFsZ29yaXRobT0iU0hBNTEyIiBzYWx0VmFsdWU9IkVC' +
  'RVNFeFFWRmhjWUdSb2JIQjBlSHc9PSIgZW5jcnlwdGVkVmVyaWZpZXJIYXNoSW5wdXQ9IkxtRzhobk1hbDg2QXYrVEkyQnlteEE9' +
  'PSIgZW5jcnlwdGVkVmVyaWZpZXJIYXNoVmFsdWU9IklPZ2xOaDNnand6Wk9zaHpJNkQxak9ycklQUDJYYXNzR2o1RGFSWXNZaHRV' +
  'eGVtR05nMG9RQkhoNk1CVUlpUlkzMFIremRnZHJhQkJtN0pQaTM2WFF3PT0iIGVuY3J5cHRlZEtleVZhbHVlPSJ2cmF2aUt3UTRY' +
  'd1VaOVBHUkkrNDBiTzFsdXNadm1ZSW9VNERpVFpxWXVZPSIvPjwva2V5RW5jcnlwdG9yPjwva2V5RW5jcnlwdG9ycz48L2VuY3J5' +
  'cHRpb24+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

/** Decode the embedded fixture to bytes. Returns a `Uint8Array<ArrayBuffer>` so
 *  `.buffer` is a plain `ArrayBuffer` a `load()` factory can accept. */
export function encryptedDocxSpin0(): Uint8Array<ArrayBuffer> {
  const bin = atob(ENCRYPTED_DOCX_SPIN0_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
